theme: jekyll-theme-minimal
title: Перепив программина
description: Скучно об увлекательном. Программист &laquo;немного за сорок&raquo; делится ненужным опытом.
show_downloads: false
timezone: Europe/Moscow
