theme: jekyll-theme-minimal
title: Перепив программина
description: Незатейливый программистский юморок, переплетённый с увлекательными рассказами о скучнейшей профессии в мире.
show_downloads: false
timezone: Europe/Moscow
