theme: jekyll-theme-minimal
title: Перепив программина
description: Скучно об увлекательном. Концентрированный опыт, потерявший актуальность десять лет назад.
show_downloads: false
timezone: Europe/Moscow
markdown: kramdown
