---
lang: ru-RU
encoding: utf-8
title: "Профессия: программист"
description: "Скучно об увлекательном: опыт, потерявший актуальность"
url: http://markshevchenko.pro
permalink: pretty
paginate: 10
paginate_path: "/posts/:num"
highlighter: rouge

exclude:
- Gemfile
- README.md

markdown: kramdown

kramdown:
  auto_ids: true

gems:
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: :compressed

defaults:
  -
    scope:
      path: "articles"
      type: "pages"
    values:
      layout: "article"
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
