theme: jekyll-theme-minimal
title: Перепившись программина
description: Зловещие тайны из жизни программиста, и в частности, рассказы о судьбе объектов, пропавших в жерле сборщика мусора; а также поучительные истории о нарушителях принципов SOLID.
show_downloads: false
is_project_page: false
is_user_page: true
